[package]
name = "clap-host-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "clap-host-rs"
path = "src/main.rs"

[dependencies]
clap-host-core = { path = "../clap-host-core" }

[build-dependencies]
slint-build = "=1.17.1"
